### ISSUE TITLE
Unable to find SC-CL

### ISSUE THREAD

**Issue by Vali0004** [maybegreat48/SC-CL#1]
I was able to generate LLVM, but I don't think the SC-CL source is even in here. Are you missing anything?

**Comment by maybegreat48** [comment]
SC-CL.exe is placed in SC-CL\llvm-14.0.0.src\MinSizeRel\bin. If you can't find it the build must have failed somehow. Please post all build logs in that case

Also the SC-CL sources are in llvm-14.0.0.src\tools\clang\tools\extra\SC-CL

**Comment by Vali0004** [comment]
Nope, not for me. I must've just removed something by accident.
Doesn't matter anymore, I just compiled an older version and updated to LLVM 14, and fixed SC-CL for vs2019

**Comment by maybegreat48** [comment]
Pushed a fix for this issue. Can you clone from scratch and see if it builds?

**Comment by Vali0004** [comment]
Just came back to this, currently downloading and extracting.

**Comment by Vali0004** [comment]
Works fine, no longer a issue.
